
server:
  port:8083


spring:
  application:
    name: ORDER-SERVICE
  datasource:
    password: admin
    url: jdbc:postgresql://localhost:5432/country
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

